### ISSUE TITLE
Create photoshop/illustrator mockup of home page design

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-screamersmovie#1]
Hello, gentleman. This should be a $299 deal with all assets provided, but he wants to see a mockup first.

Alex, can you get your design talent on a concept? One-page with watermark and an obvious place for the trailer.

This is a snippet from our first messages:

Great!  I think the best thing would be to check out the sites for some other recent successful horror movies:
Unfriended: http://www.unfriended-movie.com
The Gallows:http://thegallowsmovie.com/
It Follows:http://itfollowsfilm.com/
Our site is Screamersthemovie.com.  There’s a temp landing page up, but it’s just filler for now.
We just got our trailer ready… so that could play a big part in the design.

Let me know what I need to provide? I would like to close this sale with that mockup.

due: 
9-18-15  8p

**Comment by rodneystrong** [comment]
The other emails from @irms :+1: 

---------- Forwarded message ----------
From: Irma L. Olguin Jr. <iolguin@editllc.com>
Date: Tue, Sep 15, 2015 at 3:40 PM
Subject: Re: via Sortfolio
To: Tom Malloy <tommalloy@gmail.com>


Tom,

The layered file will help a great deal with a mockup, but I'm sending this to one of our designers now so he can start getting concepts together. Send the PSD when you get it!

Irma L. Olguin Jr.
EDIT LLC
(559) 708-6883

On Tue, Sep 15, 2015 at 2:25 PM, Tom Malloy <tommalloy@gmail.com> wrote:
Irma,

I’m sorry… waiting on a couple of things.  Here is the poster, and here is the picture that was used in the background.  I want to get the official credit block and the layered photoshop file (coming today).

I’m thinking the site can be the picture, fading out the girl (like the poster), and maybe the light bulb fades in and out?  What do you think?

Tom

![6](https://cloud.githubusercontent.com/assets/539962/9892673/e7d12500-5bc5-11e5-8e04-13f7ac039252.jpg)
![img_5116](https://cloud.githubusercontent.com/assets/539962/9892674/e7d441e0-5bc5-11e5-93de-8cb2d3b33a94.JPG)

**Comment by rodneystrong** [comment]
The rest of the emails from @irms 

On Sep 13, 2015, at 7:40 PM, Irma L. Olguin Jr. <iolguin@editllc.com> wrote:

No problem. I'll check in with you if I don't hear from you tomorrow. Have a good rest of the weekend.

Irma L. Olguin Jr.
EDIT LLC
(559) 708-6883

On Sun, Sep 13, 2015 at 4:34 PM, Tom Malloy <tommalloy@gmail.com> wrote:
Yes, I’m sorry… was waiting on a poster design that will be the backdrop of the site.  Will have it you by tomorrow.


On Sep 13, 2015, at 5:05 PM, Irma L. Olguin Jr. <iolguin@editllc.com> wrote:

Hi Tom,

Just checking in. Any luck getting those materials together?

Irma L. Olguin Jr.
EDIT LLC
(559) 708-6883

On Wed, Sep 9, 2015 at 5:48 PM, Irma L. Olguin Jr. <iolguin@editllc.com> wrote:
Hey Tom,

That sounds reasonable. I look forward to your notes tomorrow.

Have a good evening,

Irma L. Olguin Jr.
EDIT LLC
(559) 708-6883

On Wed, Sep 9, 2015 at 5:37 PM, Tom Malloy <tommalloy@gmail.com> wrote:
Okay, let’s go forward with this… I’ll get you the elements by tomorrow.

I’d like to see a sample first page before any amount is paid.  



On Sep 9, 2015, at 2:54 PM, Irma L. Olguin Jr. <iolguin@editllc.com> wrote:

Tom,

We can do this for you. Let's get it done. Our normal price for these sites start at $399, but with sortfolio, you get $100 off.

Why don't you send me everything you have (content, images, logo) and I'll make sure it gets into our pipeline to get it done. You can send me a bullet list of what you need on each page so we can get started.

I'll send you a link so you can pay online (with a credit card) when I have those things in hand. Sound good?

Irma

On Tuesday, September 8, 2015, Tom Malloy <tommalloy@gmail.com> wrote:
Great!  I think the best thing would be to check out the sites for some other recent successful horror movies:
Unfriended: http://www.unfriended-movie.com
The Gallows:http://thegallowsmovie.com/
It Follows:http://itfollowsfilm.com/

Our site is Screamersthemovie.com.  There’s a temp landing page up, but it’s just filler for now.
We just got our trailer ready… so that could play a big part in the design.

Note… this is just a low-budget indie so we’re looking for something cost-effective!


On Sep 8, 2015, at 9:01 PM, Irma L. Olguin Jr. <iolguin@editllc.com> wrote:

Hi Tom,

Of course we can. Do you have anything in mind as to the look you're going for?

Irma L. Olguin Jr.
559.708.6883
BUILDICUS {tw} {fb}

On Tue, Sep 8, 2015 at 5:57 PM, Tom Malloy <tommalloy@gmail.com> wrote:
Hello, I’m looking for a site for a indie thriller film that was shot earlier this year.  Would you be able to design a killer looking website?  We’d also like to discuss a potential social media campaign.

Best regards,

Tom Malloy
917.532.3957

**Comment by rodneystrong** [comment]
Fyi Aaron here's a link to the PSD file we just got for that movie poster that's shown in the description:
https://drive.google.com/a/editllc.com/file/d/0B88_mCI0OTGkR1lldE1oeXRaZkU/view?usp=sharing

Also, in that same folder, I included the missing font "Trajan bold"

**Comment by AaronAguilar** [comment]
UPDATE -  What I have so far - https://drive.google.com/file/d/0BwNEeMVrMpDLUWM2ajB0cFJXSzA/view?usp=sharing

**Comment by AaronAguilar** [comment]
![website](https://cloud.githubusercontent.com/assets/10875354/9972855/a881d290-5e1e-11e5-9203-23c06b9f0f6b.gif)

**Comment by rodneystrong** [comment]
Good work so far!

- Please add the text they had in the poster as well "Gigaler.com was poised to be the next billion dollar company". Make sure it's included so it makes sense next to "they didn't make it". 

In fact, I think you can do better with the design of the title and wording. Look at "The Gallows" website for inspiration.

- Add any social media icons for profiles they have. 

- I like the idea of the autoplaying clips but the client might not be able to get past the fact that you're re-using clips. Try this: incorporate some still images with the video into a masonry/isotope layout (but don't have the images/videos right next to each other, have them about 15px apart. Also, grab some different gifs so you're not re-using the same gifs. 

I've updated the due date for this

**Comment by irms** [comment]
Hi guys,

I do need something to show today. Placeholder gifs are fine and do not
need to be from the trailer itself.

**Comment by rodneystrong** [comment]
@irms  gotcha. 

@AaronAguilar  you heard the lady. I'll update the due date on this. please pull through and do not worry about having the same gif of videos; focus on the layout  and re-upload your resulting image here and to the google drive please. thank you.

**Comment by rodneystrong** [comment]
Also, if the timing of the light bulb flicker is taking you more than 10 minutes to resolve, drop it, go with what you have, and work towards finishing the other bullet points I mentioned above.

**Comment by AaronAguilar** [comment]
![full-site](https://cloud.githubusercontent.com/assets/10875354/9974333/049f7eb8-5e3f-11e5-81c6-f7b4ec46c2df.gif)

**Comment by AaronAguilar** [comment]
@rodneystrong @irms Here's what I have so far

**Comment by rodneystrong** [comment]
@AaronAguilar excellent work sir! love the edit llc quote. 
good job on the different sections; the mock-up looks more like a complete home page now. 

@irms please present this to the client.  Here's the google drive link to paste into the email: https://drive.google.com/file/d/0BwNEeMVrMpDLdWtQRHpPSThtWlU/view?usp=sharing

*fingers crossed

**Comment by rodneystrong** [comment]
@AaronAguilar some things to think about if we win this bid:

- If they don't like the blood font then have some alternatives on hand

- for the auto-playing videos section, think of a title for it, maybe "Experience Screamers"; the main point being to separate it from the top section that ends with "They didn't make it"

- the play button at the top isn't actually centered. we may have to center it and make it larger (i know you were going for covering up the light bulb)

**Comment by irms** [comment]
Thanks guys! I'll let you know how it goes!

**Comment by rodneystrong** [comment]
@AaronAguilar again, great effort and great job; client liked the mockup and wants us to finish it. 

Please upload the PSD to the google drive and comment here when you have.

**Comment by AaronAguilar** [comment]
It's uploaded!

**Comment by rodneystrong** [comment]
excellent, thank you sir
