### ISSUE TITLE
Build out the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-screamersmovie#3]
Take Aaron's final mockup from https://github.com/EditLLC/client-screamersmovie/issues/1 and code the site. 

I will have Aaron upload his PSD of the mock-up as well and have him extra all the individual media assets for you to include in the code.

You might be able to create this site from the template we've been using. 

Create a gh-pages branch as well and keep it updated with master.

due:
9-24-15   10p

new due date:
9-27-15  7p

**Comment by rodneystrong** [comment]
Raquel, The PSD and all the individual assets have been uploaded to the Drive folder. Please check the folder and add the "In Progress" label here when you've started work.

**Comment by rodneystrong** [comment]
Also, the link to the current trailer is here: 
https://vimeo.com/138108336
password: scream2015

You'll also need to create gifs from certain parts of that trailer.

**Comment by purplyrocky** [comment]
The home page is done and pushed to gh-pages. last night, aaron told me he added 2 more pages so I'm going to do those next. I think it'll take me only another hour to finish those.

**Comment by rodneystrong** [comment]
Excellent work Raquel! Unfortunately the responsiveness is broken. Please go back and resize the page and view what is happening and then adjust the CSS. 

I am updating the due date to 9-27-15  7p

**Comment by purplyrocky** [comment]
about cast, about crew and contact pages are done. I will have them all responsive by the updated due date. sorry about that, i didn't know there were 3 other pages.
