### ISSUE TITLE
Extract all media items

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-screamersmovie#4]
Crop and export all the different image and video assets @purplyrocky will need to code this site: 

- any text that's better as an image (like the title)

- the play button 

- social media icons

- the hero image

- anything else i didn't mention that needs to be extracted

Put all assets into the Drive folder

due:
9-21-15   11a

**Comment by AaronAguilar** [comment]
Uploaded Title, hero image, credits, catchphrase, and social media icons. 

The social icons could also be used using Font Awesome, the same could be said for the play button as it's where I got the images. 

Here was the inspiration website (it has the play button and trailer): http://peterfinlan.com/starnight/#


Fonts that were used are: Metamorphous Regular - (NAV), Nosifer Caps Regular - (HEADER), Trajan Pro Bold - (Body) but there's no Google fonts for it. A close alternative is: https://www.google.com/fonts/specimen/Cinzel, if nothing works, I could make the text and then export them as images.

**Comment by rodneystrong** [comment]
excellent work sir!
