### ISSUE TITLE
Code the email input form to submit

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-screamersmovie#6]
The site has an email input form near the bottom; make it behave the same way our form does on http://knotawaytherapy.com/

No need for the recaptcha, but just make sure it collects email info. Make sure it works first by having the form email you, then after you've confirmed it sends an email with the users email address, have the email sent to akang2@gmail.com and I'll test it as well. 

due:
10-7-15    11p

**Comment by purplyrocky** [comment]
@rodneystrong I've been trying to get the form to work for over an hour, I keep getting a 405 Not Allowed error

**Comment by rodneystrong** [comment]
crap, i think it's cause it's nginx and can't run php on github. could you screenshot the error your getting and post it here please?

**Comment by purplyrocky** [comment]
It takes me to this link:
http://editllc.github.io/client-screamersmovie/contact-form-handler.php

Here is the error
<img width="378" alt="screen shot 2015-10-08 at 1 47 12 am" src="https://cloud.githubusercontent.com/assets/9425509/10361693/9bc4513c-6d5e-11e5-8f20-fa0a2001832e.png">

**Comment by rodneystrong** [comment]
yea ok, no need to test it anymore. it's a github issue. 

we'll keep this issue open until we launch

**Comment by purplyrocky** [comment]
Alright
