### ISSUE TITLE
Changes from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-screamersmovie#7]
1) he’s not into the bloody “They didn’t make it.”  Could you change the font here?  Doesn’t need to be bloody.
2) We don’t have any quotes at this time because the film hasn’t been shown to anyone.  We’re changing that next week… should have some quotes by mid-week.
3) The trailer is being re-cut, so right now we want to do a "coming soon" on the trailer.

For 1) Just make it the same font as the "Gigaler.com was poised to be
the next.." text

For 2) just comment out that section in the code

For 3) hold off while I get a follow up answer from the client

due:
10-9-15   7p

**Comment by AaronAguilar** [comment]
Updated.

Used the same text as Gigaler for "They didn't make it" - used the title font for Mail sign up. Added another gif. 

Do I take off the play button? What did they client say?
